### ISSUE TITLE
Making GET requests to /userCategories every time homepage (not category page) is hit.

### ISSUE THREAD

**Issue by Ollynov** [versatile-s/hyperspace#191]

**Comment by kiraknowsbest** [comment]
fixed this, waiting to put in pull request

**Comment by Ollynov** [comment]
@kiraknowsbest Are you sure this is fixed? Seems to still be an issue for me

**Comment by kiraknowsbest** [comment]
I still don't see this happening. I have a console log in the server and I don't see it getting hit at login or signup
